### ISSUE TITLE
Failed to run tests with fastapi templates on Linux and Mac

### ISSUE THREAD

**Issue by v-jiaodi** [Azure-Samples/azure-fastapi-postgres-flexible-aca#12]
**Describe the issue:**
When test `Running tests` with fastapi templates on Linux and Mac, run `python3 -m pytest`, get error as follow:
![image](https://github.com/Azure-Samples/azure-fastapi-postgres-flexible-aca/assets/80496810/dba7e306-8201-4dda-bd22-6578a32fcadc)

**Repro Steps:**
1. Clone the repo to local.
2. Create a [Python virtual environment](https://docs.python.org/3/tutorial/venv.html#creating-virtual-environments) and activate it.
3. Install requirements: 
`python3 -m pip install -r requirements-dev.in`
`playwright install --with-deps`
4. Run the tests: `python3 -m pytest`
  

**Environment:**

- OS: Linux and Mac.
- Azd version: 1.4.1  (commit https://github.com/Azure/azure-dev/commit/1cbed85cf47ed235b5ed31868eda79619525bfcc)
- Python : 3.8
- Template: 
https://github.com/Azure-Samples/azure-fastapi-postgres-flexible-aca
https://github.com/Azure-Samples/azure-fastapi-postgres-flexible-appservice
https://github.com/Azure-Samples/azure-fastapi-cosmos-postgres-aca
https://github.com/Azure-Samples/azure-fastapi-cosmos-postgres-appservice
https://github.com/Azure-Samples/azure-fastapi-postgres-addon-aca

**Expected behavior:**
Running `python3 -m pytest` with flask templates can pass on Linux and Mac.

 @pamelafox  for notification.

**Comment by pamelafox** [comment]
Can you copy and paste the full error message? (That starts with SSL error) You might also need to scroll up.

**Comment by pamelafox** [comment]
Did you set up a Postgres database locally with the correct username/password? (The same as what would have been setup by the dev container)

**Comment by v-jiaodi** [comment]
@pamelafox  I set up a Postgres database locally with the correct username/password, the full error message as follow:
![image](https://github.com/Azure-Samples/azure-fastapi-postgres-flexible-aca/assets/80496810/c5f3ef47-8cea-4aac-b078-5bd5e686eaf5)

**Comment by pamelafox** [comment]
I made various updates to the tests and also added instructions for running Postgres locally. Can you try it again?

If you're still getting an SSL error, I wonder why it's trying to use SSL. You could try explicitly setting a local environment variable of POSTGRES_SSL to "disable".

**Comment by pamelafox** [comment]
Another thought - if you're still getting SSL issues, can you try changing line 19 in models to py to:

```
if os.environ.get("POSTGRES_HOST") == "localhost":
    sql_url = f"{sql_url}?sslmode=disable"
```

**Comment by v-jiaodi** [comment]
Test again, the current issue no longer exists.
