### ISSUE TITLE
Abnormal running fastapi app on CodeSpace

### ISSUE THREAD

**Issue by v-jiaodi** [Azure-Samples/azure-fastapi-postgres-flexible-aca#13]
**Describe the issue:**
When test `Running Locally` with fastapi templates on CodeSpace, run `python3 -m gunicorn fastapi_app:app -c src/gunicorn.conf.py`, Web page loading exception:
![image](https://github.com/Azure-Samples/azure-fastapi-postgres-flexible-aca/assets/80496810/2e5b0285-0898-4de1-ba4b-2294121aa4be)

**Repro Steps:**
1. Open with CodeSpace
2. Run `python3 -m gunicorn fastapi_app:app -c src/gunicorn.conf.py`.
  

**Environment:**

- OS: CodeSpace.
- Azd version: 1.4.1  (commit https://github.com/Azure/azure-dev/commit/1cbed85cf47ed235b5ed31868eda79619525bfcc)
- Template: 
https://github.com/Azure-Samples/azure-fastapi-postgres-flexible-aca
https://github.com/Azure-Samples/azure-fastapi-postgres-flexible-appservice
https://github.com/Azure-Samples/azure-fastapi-cosmos-postgres-aca
https://github.com/Azure-Samples/azure-fastapi-cosmos-postgres-appservice
https://github.com/Azure-Samples/azure-fastapi-postgres-addon-aca

**Expected behavior:**
Running `python3 -m gunicorn fastapi_app:app -c src/gunicorn.conf.py` with flask templates, the web page can load normally on CodeSpace.
 @pamelafox  for notification.

**Comment by pamelafox** [comment]
Looks like a static assets issue. cc @kjaymiller

**Comment by v-jiaodi** [comment]
@kjaymiller  This issue still exist.

**Comment by pamelafox** [comment]
@v-jiaodi I think we failed to merge the fixes into main, which we've now done. Could you take another look to see if it's fixed now?

**Comment by v-jiaodi** [comment]
@pamelafox This issue still exist.

**Comment by pamelafox** [comment]
I have just confirmed this is fixed in Codespaces.

**Comment by pamelafox** [comment]
Please confirm on your end as well that it seems fixed.
